# Application bindings
$terminal = uwsm app -- ghostty -e fish
$browser = uwsm app -- brave --new-window --ozone-platform=wayland
$webapp = $browser --app

bindd = SUPER, return, Terminal, exec, $terminal
bindd = SUPER, B, Browser, exec, $browser

