background {
  monitor =
  color = rgb(17, 17, 17)
}

input-field {
  monitor =
  size = 320, 42
  position = 0, 0
  halign = center
  valign = center

  outline_thickness = 1
  outer_color = rgba(42, 42, 42, 0.85)
  inner_color = rgba(18, 18, 18, 0.96)
  font_color = rgb(238, 238, 238)
  fail_color = rgb(184, 74, 74)
  check_color = rgb(153, 153, 153)

  fade_on_empty = false
  placeholder_text = Password
  hide_input = false
  font_size = 18
}

label {
  monitor =
  text = locked
  color = rgb(238, 238, 238)
  font_family = Berkeley Mono
  font_size = 14
  position = 0, 54
  halign = center
  valign = center
}
