# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/autostart.conf

# Extra autostart processes
# exec-once = dropbox-cli start

# Extra env variables
# Note: You must relaunch Hyprland after changing envs (use Super+Esc, then Relaunch)
# env = MY_GLOBAL_ENV,setting

# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Alt + Space
  # kb_layout = us,dk
  # kb_options = compose:caps,grp:alt_space_toggle

  # Change speed of keyboard repeat
  repeat_rate = 67
  repeat_delay = 180

  # Increase sensitity for mouse/trackpack (default: 0)
  # sensitivity = 0.35

  touchpad {
    # Use natural (inverse) scrolling
    # natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }
}

# custom overrides
unbind = SUPER, W
bind = SUPER, Q, killactive

# override Super+J/K for cycling and swapping windows
unbind = SUPER, J
unbind = SUPER, K
bind = SUPER, J, cyclenext
bind = SUPER, K, cyclenext, prev
bind = SUPER SHIFT, J, swapnext
bind = SUPER SHIFT, K, swapnext, prev

# layout resizing 
binde = SUPER, H, resizeactive, -50 0
binde = SUPER, L, resizeactive, 50 0

# disable all animations
animations {
    enabled = false
}

# remove gaps between windows and around screen edges
general {
    gaps_in = 0
    gaps_out = 0
    border_size = 0
}

# don't save screenshots
# bind = SUPER SHIFT, S, exec, grim -g "$(slurp)" - | satty --filename -
bind = SUPER SHIFT, S, exec, grim -g "$(slurp)" - | satty --filename - --copy-command 'wl-copy --type image/png' --actions-on-enter save-to-clipboard,exit

# screen recording
bind = SUPER SHIFT, V, exec, ~/.local/share/omarchy/bin/omarchy-cmd-screenrecord
