theme = "dark-transparent"

hide_quick_activation = true
hide_action_hints = true
hide_return_action = true
actions_as_menu = false

[providers]
default = ["desktopapplications", "calc", "menus"]

[providers.actions]
desktopapplications = [
  { action = "start", default = true, bind = "Return", after = "Close" },
]

runner = [
  { action = "run", default = true, bind = "Return", after = "Close" },
]

menus = [
  { action = "activate", default = true, bind = "Return", after = "Close" },
]

providerlist = [
  { action = "activate", default = true, bind = "Return", after = "ClearReload" },
]
